introduction/urls.py
from django.urls import path
from . import views

app_name="introduction"
urlpatterns = [
    path('', views.profile, name="profile"),
    path('drama/', views.drama, name="drama"),
    path('pictures/', views.pictures, name="pictures"),
    path('music/', views.music, name="music"),
    path('album/', views.album, name="album"),
    path('cafe/', views.cafe, name="cafe"),
    path('edam/', views.edam, name="edam"),


]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('introduction/', include('introduction.urls')),
    path('', views.main, name="main"),
    path('posts/', include('posts.urls')),
    
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import *


app_name="posts"
urlpatterns=[
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('', main, name="main"),
    path('show/<int:id>/', show, name="show"),
    path('edit/<int:id>/', update, name="update"),
    path('delete/<int:id>/', delete, name="delete"),
    path('create_comment/<int:post_id>/', create_comment, name="create_comment")
]

introduction/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post (models.Model):
    title = models.CharField(max_length=50, null=False)
    content = models.TextField()
    view_count = models.IntegerField(default=0)
    image = models.ImageField(upload_to='images/', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)


class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']
        labels = {
            'title: 제목',
            'content: 내용'
        }
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'content': forms.Textarea(attrs={
                'class': 'form-control'
            }),
        }

introduction/views.py
from django.shortcuts import render

# Create your views here.
def profile(request):
    return render(request, 'introduction/profile.html')

def drama(request):
    return render(request, 'introduction/drama.html')

def pictures(request):
    return render(request, 'introduction/pictures.html')

def music(request):
    return render(request, 'introduction/music.html')

def album(request):
    return render(request,'introduction/album.html')    
   
def cafe(request):
    return render(request,'introduction/youandi.html')   

def edam(request):
    return render(request,'introduction/edam.html')   
       
    

myblog/views.py
from django.shortcuts import render

def main(request):
    return render(request, 'main.html')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import PostForm

# Create your views here.
def new(request):
    form = PostForm()
    context = {
        'form':form
    }
    return render(request, 'posts/new.html', context)

def create(request):   
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        user = request.user
        Post.objects.create(title=title, content=content, image=image, user=user)
    return redirect('posts:main')

def main(request):
    context = {
        'posts' : Post.objects.all().order_by('-created_at')
    }
    return render(request, 'posts/main.html', context)    

def show(request, id):
    post = get_object_or_404(Post, pk=id)
    post.view_count = post.view_count +1
    post.save()
    all_comments = post.comments.all().order_by('-created_at')  ### -는 내림차순
    return render(request, 'posts/show.html', {"post":post, 'comments':all_comments}) 


def update(request, id):   
    post = get_object_or_404(Post, pk=id)
    if request.method == "POST":
        post.title = request.POST['title']
        post.content = request.POST['content']
        post.image = request.FILES.get('image')
        post.save()
        return redirect('posts:show', post.id)
    return render(request, 'posts/edit.html', {'post':post})

def delete(request, id):
    post = get_object_or_404(Post, pk=id)
    post.delete()
    return redirect('posts:main')

def create_comment(request, post_id):
    if request.method == "POST":
        post = get_object_or_404(Post, pk = post_id)
        current_user = request.user
        comment_content = request.POST.get('content')
        Comment.objects.create(content=comment_content, user= current_user, post= post)
        ########## if가 실행 될 때
    return redirect('posts:show', post.pk)    ##앱 이름 : show로! >>post.pk를 같이 갖고 간다.
    
    ####### post가 아닐 경우에도 실행됨

introduction/templates/introduction/aboutiu.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
{% include 'shared/navbar.html' %}
<link href="https://fonts.googleapis.com/css2?family=Nunito:ital@1&display=swap" rel="stylesheet">
<link
    href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,500;1,600&family=Heebo:wght@300&family=Inconsolata:wght@500&family=Lobster&family=Merienda+One&family=Permanent+Marker&family=Poor+Story&family=Quicksand:wght@500&display=swap"
    rel="stylesheet">
<link
    href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,500;1,600&family=Heebo:wght@300&family=Inconsolata:wght@500&family=Lobster&family=Merienda+One&family=Permanent+Marker&family=Quicksand:wght@500&display=swap"
    rel="stylesheet">
<link
    href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,500;1,600&family=Heebo:wght@300&family=Inconsolata:wght@500&family=Merienda+One&family=Permanent+Marker&family=Quicksand:wght@500&display=swap"
    rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Merienda+One&family=Quicksand:wght@500&display=swap"
    rel="stylesheet">




<img src="{%static 'images/iuiu.jpg'%}" width="50px" height="50px"/>



<div id="right">
    <h1>Profile</h1>
    <h2>이름: 아이유 (이지은, IU)</h2>
    <h2>나이: 28세 (만 27세)</h2>
    <h2>출생: 1993년 5월 16일</h2>
    <h2>소속사: EDAM엔터테인먼트</h2>
    <h2>데뷔: 2008년 미니 앨범 [Lost and Found]</h2>
    <br />
    <br />
    <a href="https://www.instagram.com/dlwlrma/">Instagram</a>
    <a href="https://www.youtube.com/dlwlrma">Youtube</a>
    <a href="https://www.facebook.com/iu.loen">Facebook</a><br /><br />
    <a href="https://twitter.com/_IUofficial">Twitter</a>
    <a href="https://channels.vlive.tv/FA895/home">V Live</a>
</div>





{% endblock%}

introduction/templates/introduction/album.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'shared/navbar.html' %}
<link href="https://fonts.googleapis.com/css2?family=Monoton&display=swap" rel="stylesheet">


<iframe src="https://vibe.naver.com/artist/112579/albums" width="100%" height="1000px"></iframe>



{% endblock %}

introduction/templates/introduction/drama.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'shared/navbar.html' %}
<link
href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,500;1,600&family=Heebo:wght@300&family=Inconsolata:wght@500&family=Lobster&family=Merienda+One&family=Permanent+Marker&family=Quicksand:wght@500&display=swap"
rel="stylesheet">
<link
  href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,500;1,600&family=Heebo:wght@300&family=Inconsolata:wght@500&family=Lobster&family=Merienda+One&family=Permanent+Marker&family=Poor+Story&family=Quicksand:wght@500&display=swap"
  rel="stylesheet">


<div id="dtitle">
  <h1>Drama</h1>
</div>

<div id="a"><img src="{%static 'images/i.gif'%}" width=100%></div>



<div class="card" style="width: 18rem;">
  <img src="{%static 'images/deluna.jpg'%}" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">호텔 델루나</p>
    <p class="card-text">장만월 (주연)</p>
    <p class="card-text">2019</p>
  </div>
</div>



<div class="card" style="width: 18rem;">
  </br>
  </br>

  <img src="{%static 'images/my.jpg'%}" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">나의 아저씨</p>
    <p class="card-text">이지안 (주연)</p>
    <p class="card-text">2018</p>
  </div>
</div>

<div class="card" style="width: 18rem;">
  </br>
  </br>

  <img src="{%static 'images/bo.jpg'%}" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">달의 연인 - 보보경심 려</p>
    <p class="card-text">해수 (주연)</p>
    <p class="card-text">2016</p>
  </div>
</div>

<div class="card" style="width: 18rem;">
  </br>
  </br>

  <img src="{%static 'images/pro.png'%}" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">프로듀사</p>
    <p class="card-text">신디 (주연)</p>
    <p class="card-text">2015</p>
  </div>
</div>

<div class="card" style="width: 18rem;">
  </br>
  </br>

  <img src="{%static 'images/pp.png'%}" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">예쁜남자</p>
    <p class="card-text">김보통 (주연)</p>
    <p class="card-text">2013~2014</p>
  </div>
</div>

<div class="card" style="width: 18rem;">
  <img src="{%static 'images/p.jpg'%}" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">촤고다 이순신</p>
    <p class="card-text">이순신 (주연)</p>
    <p class="card-text">2013</p>
  </div>

</div>

<div class="card" style="width: 18rem;">
  </br>
  </br>

  <img src="{%static 'images/dreamh.jpg'%}" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">드림하이</p>
    <p class="card-text">김필숙 (주연)</p>
    <p class="card-text">2011</p>
  </div>
</div>

{% endblock %}

introduction/templates/introduction/edam.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
{% include 'shared/navbar.html' %}


<iframe src="http://madeedam.com/" width=100% height=1000></iframe>


{% endblock %}

introduction/templates/introduction/music.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'shared/navbar.html' %}

<head>

</head>

<body>

<h1>hd</h1>
    <audio controls>
        <source src="https://www.genie.co.kr/player/fPlayer" controls type="audio/mpeg">
    </audio>
</body>






{% endblock %}

introduction/templates/introduction/pictures.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'shared/navbar.html' %}

<head>

    <link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
    <link rel="stylesheet" href="http://cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css">
    <link rel="stylesheet" href="{% static 'css/pictures.css'%}">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script type="text/javascript" src="http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

   
</head>

<body>



    <section class="visual">
        <div><img src="{%static 'images/iu2.jpg'%}" width="100%" ></div>
        <div><img src="{%static 'images/iuiui.jpeg'%}"width="90%"></div>
        <div><img src="{%static 'images/iu5.jpg'%}"width="90%" ></div>
        <div><img src="{%static 'images/iuu.png'%}"width="90%"></div>
    </section>


    <script type="text/javascript">
        $('.visual').slick();
    </script>
</body>
{% endblock %}

introduction/templates/introduction/profile.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
{% include 'shared/navbar.html' %}

<head>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital@1&display=swap" rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,500;1,600&family=Heebo:wght@300&family=Inconsolata:wght@500&family=Lobster&family=Merienda+One&family=Permanent+Marker&family=Poor+Story&family=Quicksand:wght@500&display=swap"
        rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,500;1,600&family=Heebo:wght@300&family=Inconsolata:wght@500&family=Lobster&family=Merienda+One&family=Permanent+Marker&family=Quicksand:wght@500&display=swap"
        rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,500;1,600&family=Heebo:wght@300&family=Inconsolata:wght@500&family=Merienda+One&family=Permanent+Marker&family=Quicksand:wght@500&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Merienda+One&family=Quicksand:wght@500&display=swap"
        rel="stylesheet">

</head>

<body>
    <div id="left">
        <img src="{%static 'images/iuiu.jpg'%}" width="85%" />

    </div>


    <div id="right">
        <h1>Profile</h1>
        <br />
        <h2>이름: 아이유 (이지은, IU)</h2>
        <h2>나이: 28세 (만 27세)</h2>
        <h2>출생: 1993년 5월 16일</h2>
        <h2>소속사: EDAM엔터테인먼트</h2>
        <h2>데뷔: 2008년 미니 앨범 [Lost and Found]</h2>
        <br />
        <br />
        <a href="https://www.instagram.com/dlwlrma/">Instagram</a>
        <a href="https://www.youtube.com/dlwlrma">Youtube</a>
        <a href="https://www.facebook.com/iu.loen">Facebook</a><br /><br />
        <a href="https://twitter.com/_IUofficial">Twitter</a>
        <a href="https://channels.vlive.tv/FA895/home">V Live</a>
    </div>
</body>




{% endblock%}

introduction/templates/introduction/youandi.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
{% include 'shared/navbar.html' %}

<iframe src="http://cafe420.daum.net/_c21_/home?grpid=1I7Yc" width=100% height=1000></iframe>



{% endblock %}

myblog/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>IU Official</title>
  </head>
  <body>
    
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

myblog/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'shared/navbar.html' %}
<link href="https://fonts.googleapis.com/css2?family=Merienda+One&display=swap" rel="stylesheet">


<div id="main">
    <div id="contents">
        <h1>IU</h1>
        <p>Official Website</p>
        <a href="{% url 'introduction:profile'%}"> About IU </a>
    </div>
</div>
{% endblock %}

myblog/templates/shared/navbar.html
<link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,500;1,600&family=Heebo:wght@300&family=Inconsolata:wght@500&family=Lobster&family=Merienda+One&family=Permanent+Marker&family=Quicksand:wght@500&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Merienda+One&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Nunito:ital@1&family=Oleo+Script:wght@700&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Nunito:ital@1&family=Oleo+Script:wght@700&family=Shrikhand&display=swap" rel="stylesheet">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{%url 'main'%}">IU Official</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{%url 'introduction:pictures'%}">Home <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{%url 'introduction:profile'%}">Profile</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Biography
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{%url 'introduction:album'%}">Album</a>
            <a class="dropdown-item" href="{% url 'introduction:drama'%}">Drama</a>
          </div>
        </li>



        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            ❤
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{%url 'introduction:cafe'%}">Fan Cafe</a>
            <a class="dropdown-item" href="{%url 'introduction:edam'%}">EDAM Ent.</a>
            <!-- <div class="dropdown-divider"></div> -->
            <!-- <a class="dropdown-item" href="#">Something else here</a> -->
          </div>
        </li>


        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Fan Letter
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{%url 'posts:new'%}">writing a fan letter</a>
            <a class="dropdown-item" href="{%url 'posts:main'%}">letters</a>
            <!-- <div class="dropdown-divider"></div> -->
            <!-- <a class="dropdown-item" href="#">Something else here</a> -->
          </div>
        </li>


        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_change_password' %}">Change PW</a>
          </li>

        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
          </li>

        {% endif %}
      

        

        <!-- <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li> -->
      </ul>
      <!-- <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form> -->
    </div>
  </nav>

posts/templates/posts/edit.html
{% extends 'base.html' %}
{% block content %}
{% include 'shared/navbar.html' %}
<link href="https://fonts.googleapis.com/css2?family=Yeon+Sung&display=swap" rel="stylesheet">
 
<div class="container">
    <h1>팬레터 쓰기</h1>
    <div class="form">
        <form action="{% url 'posts:update' post.id %}" method="POST" enctype="multipart/form-data"> 
            {% csrf_token %} 
            <div class="form-group">
                 <label>글 제목</label> 
                <input type="text" class="form-control" name="title" id="title" placeholder="제목을 입력해 주세요" value = "{{ post.title }}"> 
            </div>
             <div class="form-group">
                <label>글 내용</label>
                <textarea class="form-control" name="content" id="content" placeholder="내용을 입력해 주세요">{{post.content}}</textarea>
             </div>
             <input type="file",  name="image"  accept="image/*">
             <input type="submit" value="글 수정" class="btn btn-outline-primary">
         </form> 
    
    </div>
</div>

{% endblock %}

posts/templates/posts/main.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% include 'shared/navbar.html' %}
    {% if user.is_authenticated %}
        <link href="https://fonts.googleapis.com/css2?family=Yeon+Sung&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Gamja+Flower&display=swap" rel="stylesheet">
        <img src="{% static 'images/hh.jpg'%}"  style="margin-left: 23.5%;">

        <div class="container">
        <h1>팬레터</h1><br>
        <div class="item">
            <a href="{%url 'posts:new' %}" class="btn btn-primary">새 글 쓰기</a>
        </div>
        <div class="row">
            {% for post in posts %}
            <div class="col-md-4 col-12">
                <div class="card" style="width: 15rem; margin-top:20px;">
                    <div class="card-body" >
                        <h5 class="card-title" style="color: indigo;">
                            제목:{{post.title}}
                        </h5>
                        <p class="card-text" style="color: indigo;">
                            내용:{{post.content}}
                        </p>
                        <p style="color: indigo;">
                            {{post.created_at}}
                        </p>
                        <p style="color: indigo;">
                            조회수:{{post.view_count}}
                        </p>
                        <br />
                        <a href="{% url 'posts:show' post.id %}" class="btn btn-primary">상세보기</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        </div>

    {% else %}
    <h3> 로그인 후 이용이 가능합니다. </h3> 
    <a href="{% url 'account_login' %}" class= "btn btn-warning">로그인</a>
    <a href="{% url 'account_signup' %}" class= "btn btn-warning">회원가입</a>
    {% endif %}


{% endblock %}

posts/templates/posts/new.html
{% extends 'base.html' %}
{% block content %}
{% include 'shared/navbar.html' %}

<link href="https://fonts.googleapis.com/css2?family=Yeon+Sung&display=swap" rel="stylesheet">

<div class="container">
    <h1>팬레터 쓰기</h1>
    <div class="form">
        <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <br/>
            <input type="file" name="image"  accept="image/*">
            <br/>
            <br/>

            <input type="submit" value="글 작성" class="btn btn-outline-primary">
        </form>
    </div>
</div>

{% endblock %}

posts/templates/posts/show.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'shared/navbar.html'%}
<link href="https://fonts.googleapis.com/css2?family=Yeon+Sung&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Gamja+Flower&display=swap" rel="stylesheet">


<div id="detail">
    <div id="detailcontents">
        <h3>제목: {{post.title}}</h3><br>
        <h3>내용: {{post.content}}</h3><br>
        <h3>작성 시각:{{post.created_at}}</h3>
        <h3>조회수:{{post.view_count}}</h3>
        {% if post.user %}
            {% if post.user.username == 'user' %}
            <h3>작성자: {{post.user.last_name}} {{post.user.first_name}}</h3>
            {% else %}
            <h3>작성자: {{post.user}}</h3><br>
            {% endif %}
        {% else %}
        <h3>작성자: 알 수 없음</h3><br>
        {% endif %}
      

   
        <br>
        <br>
        {% if user == post.user %}
        <a href="{% url 'posts:update' post.pk %}" class="btn btn-outline-primary">수정하기</a>
        <a href="{% url 'posts:delete' post.pk %}" class="btn btn-outline-primary">삭제하기</a>
        {% endif %}

        

    </div>
    

    <div id="pic">
        {% if post.image %}
             <img src="{{ post.image.url }}" alt="사진" width="30%" height="30%">
        {% endif %}
    </div>
</div>

    
<div class="container mt-5">
    <form class="form-row" action="{% url 'posts:create_comment' post.id %}" method="POST" >
        {% csrf_token %}
        <textarea class="form-control col-11 mr-2" name="content" placeholder="댓글 입력"></textarea>
        <input type="submit" class="btn btn-primary" value="확인">
    </form>
</div>    

<div class="container mt-5 mb-5">
    {% for comment in comments %}
    <div class="card">
        <div class="card-body">
            <b>{{comment.user}}</b> : {{comment.content}}<br>
            <small> {{comment.created_at}} </small>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% block content %}
{% include 'shared/navbar.html' %}
<link href="https://fonts.googleapis.com/css2?family=Yeon+Sung&display=swap" rel="stylesheet">
 
<div class="container">
    <h1>팬레터 쓰기</h1>
    <div class="form">
        <form action="{% url 'posts:update' post.id %}" method="POST" enctype="multipart/form-data"> 
            {% csrf_token %} 
            <div class="form-group">
                 <label>글 제목</label> 
                <input type="text" class="form-control" name="title" value = "{{ post.title }}"> 
            </div>
             <div class="form-group">
                 <label>글 내용</label>
                 <textarea class="form-control" name="content"> {{ post.content }} </textarea>
             </div>
             <input type="file" name="image" >
             <input type="submit" value="글 수정" class="btn btn-outline-primary">
         </form> 
    
    </div>
</div>

{% endblock %}